### ISSUE TITLE
无法支持https服务转发

### ISSUE THREAD

**Issue by ddzyan** [eshengsky/noginx#4]
```bash
0|server  | TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
0|server  |     at new ClientRequest (_http_client.js:118:11)
0|server  |     at Object.request (https.js:280:10)
0|server  |     at Array.stream (/data/noginx/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:126:74)
0|server  |     at ProxyServer.<anonymous> (/data/noginx/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
0|server  |     at proxyWeb (/data/noginx/proxyWeb.js:253:19)
0|server  |     at routeHandler (/data/noginx/server.js:311:17)
0|server  |     at cacheHandler (/data/noginx/server.js:256:13)
0|server  |     at app.use (/data/noginx/server.js:437:5)
0|server  |     at Layer.handle [as handle_request] (/data/noginx/node_modules/express/lib/router/layer.js:95:5)
0|server  |     at trim_prefix (/data/noginx/node_modules/express/lib/router/index.js:317:13)
0|server  |     at /data/noginx/node_modules/express/lib/router/index.js:284:7
0|server  |     at Function.process_params (/data/noginx/node_modules/express/lib/router/index.js:335:12)
0|server  |     at next (/data/noginx/node_modules/express/lib/router/index.js:275:10)
0|server  |     at favicon (/data/noginx/node_modules/serve-favicon/index.js:68:7)
0|server  |     at Layer.handle [as handle_request] (/data/noginx/node_modules/express/lib/router/layer.js:95:5)
0|server  |     at trim_prefix (/data/noginx/node_modules/express/lib/router/index.js:317:13)

```

**Comment by rowthan** [comment]
https 需要自己配ssl证书

**Comment by ddzyan** [comment]
我转发的目标地址是HTTPS协议，noginx这需要怎么配置呢

**Comment by rowthan** [comment]
> 我转发的目标地址是HTTPS协议，noginx这需要怎么配置呢

要自己申请https证书，然后在 /config/producction.js ssl 中配置。比较麻烦

**Comment by eshengsky** [comment]
@rowthan 更新下代码，现在可以转发到https服务，无需额外配置。
